import:
  - status/*.yaml
  - control/*.yaml
  - control/action/*.yaml
  - display/*.yaml
  - display/color/zenburn.yaml
  - display/desktop/feh.yaml

prefer:
  terminal: urxvtcd
  browser: firefox
  editor: gvim
  filer: thunar

display:
  bar: top
  font: "xft:Sans-10"
  border: 1
  column:
    mode: default
    rule: |
      /gimp/ -> 17+83+41
      /chat/ -> 17+83+41
      /.*/ -> 50+50
  client:
    rule: |
      /^chromium:Chromium:Chromium Preferences$/ floating=on
      /^chromium:Chromium:Task Manager/ floating=on
      /^chromium:/ group=0
      /Mozilla Thunderbird$/ tags=mail
      /^firefox:/ group=0
      /^gimp:/ tags=gimp
      /^liferea:/ tags=feed
      /:MPlayer:/ floating=on
      /^<nil>:<nil>:Event Tester$/ floating=on # xev
      /^pcmanfm:/ group=0
      /^pinentry/ floating=on
      /^skype:|^Pidgin:/ tags=chat allow=+activate
      /^sonata:/ tags=1 allow=+activate
      /Thunar:File Operation Progress/ floating=on
      /^tkmidity/ floating=on
      /^vncviewer:/ floating=on
      /^xmag:/ floating=on
      /^xmessage:/ floating=on tags=/./
      /^Spotify( Premium)? - Linux Preview/ tags=music

  refresh: 30
  status:
    - notice:
        control:
          action:
            show_desktop: focus_view '...'
          mouse_action:
            right_click: show_desktop
            wheel_up: focus_next_view
            wheel_down: focus_previous_view
    - arrange:
        params:
          choices:
            right_stack: |
              tile_right
              managed_areas.last.layout = :stack
    - weather:
        refresh: 300
        params:
          location: SJC
    - volume:
        params:
          mixer: Master
    - disk:
    - network:
    - thermal:
    - loadavg:
    - battery:
    - clock:
        params:
          format: '%l:%M%P %a %m/%d'

#script:
#  - after: |
#      launch 'witray'
#      launch 'clipit'
#      launch 'gnome-settings-daemon'
#      launch 'pidgin'
#      launch 'dropbox start'
#      launch '/home/amukherjee/bin/wallpaper.sh'

control:
  keyboard:
    root:     Mod4-
    send:     ${root}Shift-
    size:     ${root}Control-
    swap:     ${root}w,
    view:     ${root}v,
    group:    ${root}g,
    layout:   ${root}z,
  keyboard_action:
    ${root}x:          terminal
    ${root}i:          browser
#    view:    Mod4-Shift-v
#    move:    Mod4-Shift
#    swap:    Mod4-r
#    group:   Mod4-g
#    layout:  Mod4-z
#    arrange: Mod4-Shift-z
#    resize:  Mod4-Control
  action:
    terminal: launch 'urxvt'
    browser: launch 'firefox'
    editor: launch 'gvim'
    filer: launch 'thunar'

    autotop: | # recover from bad xrandr
      if system 'xrandr | fgrep -q "HDMI1 connected"'
        action 'desktop'
      else
        system 'xrandr --auto --dpi 96'
        system 'xset dpms force on' # wake up monitor from power saving mode
      end

    portrait: | # rotate screen vertically
      system 'xrandr -o left && xrandr --dpi 96'

    landscape: | # rotate screen horizontally
      system 'xrandr -o normal && xrandr --dpi 96'

    lock: | # lock with ss
      system 'gnome-screensaver-command --lock'
