import:
  - status/*.yaml
  - status/music/spotify.yaml
  - control/*.yaml
  - control/action/*.yaml
  - display/*.yaml
  - display/color/zenburn.yaml
  - display/desktop/feh.yaml

display:
  bar: top
  font: "xft:Sans-10"
  border: 1
  column:
    mode: default
    rule: |
      /gimp/ -> 17+83+41
      /chat/ -> 17+83+41
      /.*/ -> 50+50
  client:
    rule: |
      /^wimenu:|^wmii9menu:/ tags=/./
      /^xmessage:/ tags=/./ floating=on
      /^Eclipse:/ floating=off tags=eclipse
      /^xwrits:/ tags=/./
      /^xfce4-notifyd:/ tags=/./

      /^<nil>:<nil>:Event Tester$/ floating=on # xev
      /^x/ floating=on
      /^pinentry/ floating=on
      /^spotify:/ tags=music
      /^display:/ floating=on
      /:Mplayer:/ floating=on
      /Thunar:File Operation Progress/ floating=on
      /^tkmidity/ floating=on
      /^vncviewer:/ floating=on

      /^sonata:/ tags=1 allow=+activate

      /^skype:/ tags=chat allow=+activate
      /^Pidgin:/ tags=chat allow=+activate
      /^Mail:/ tags=mail

      /^liferea:/ tags=feed

      /^gimp:/ tags=gimp floating=on

      /^claws-mail:/ tags=mail

      /^zim:/ tags=note

      /^rdesktop:/ tags=work floating=on
      /^google-chrome:/ floating=off
      /^chromium-browser:/ floating=off

      /^firefox:/ group=0

      /^pcmanfm:/ group=0

  refresh: 30
  status:
    - notice:
        control:
          action:
            show_desktop: focus_view '...'
            status_refresh: $status_barlets.each(&:refresh)
          mouse_action:
            right_click: show_desktop
            wheel_up: focus_view_next
            wheel_down: focus_view_previous
            wheel_click: status_refresh
    - music:
    - arrange:
        params:
          default: landscape
          choices:
            landscape: |
              a = columns.first
              if a.exist? and a.length == 2 and a.next.floating?
                a.length = 1
              end

            right_stack: |
              tile_right
              columns.last.layout = :stack
    - weather:
        refresh: 300 # 5 minutes
        params:
          location: SJC
    - volume:
        params:
          mixer: Master
    - disk:
        params:
          path: /
    #- network:
        #params:
          #interface: wlan0
    - network:
        params:
          interface: eth0
    #- memory:
    - loadavg:
        params:
          critical: 8.0
          high: 5.0
    - clock:
        params:
          format: '%l:%M%P %a %m/%d'
        control:
          action:
            time_month_calendar: |
              dialog `cal -h`.sub(/\b#{Time.now.day}\b/) {|s| '*' * s.length}
            time_year_calendar: |
              dialog `cal -y -h`.sub(/^.*$/) {|line| Date.today.to_s.center(line.length) }

script:
  after: |
    launch '/home/amukherjee/bin/wallpaper.sh'

control:
  action:
    negative: launch! 'xcalib -invert -alter'
    terminal: launch 'urxvtcd'
    browser:  launch 'google-chrome'
    filer:    launch 'thunar'
    editor:   launch 'gvim'
    nein:     launch '/home/amukherjee/bin/nein'

    desktop: | # dock laptop to my desk
      system 'xrandr --output HDMI1 --auto --output LVDS1 --off --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode
      system 'setxkbmap us -option ""' # switch to QWERTY for keyboard
      system 'marble-mouse left'
      action 'reload' # reposition witray & update shortcuts to new xkbmap

    laptop: | # undock laptop from my desk
      system 'xrandr --output LVDS1 --auto --output HDMI1 --off --output VGA1 --off --dpi 96'
      system 'setxkbmap dvorak -option ""' # switch to QWERTY for keyboard
      action 'music_pause'
      action 'reload' # reposition witray & update shortcuts to new xkbmap

    projector: | # display through a projector
      system 'xrandr --output VGA1 --auto --output LVDS1 --off --dpi 96'
      system 'xset dpms force on' # wake up monitor from power saving mode

    autotop: | # recover from bad xrandr
      if system 'xrandr | fgrep -q "HDMI1 connected"'
        action 'desktop'
      else
        system 'xrandr --auto --dpi 96'
        system 'xset dpms force on' # wake up monitor from power saving mode
      end

    portrait: | # rotate screen vertically
      system 'xrandr -o left && xrandr --dpi 96'

    landscape: | # rotate screen horizontally
      system 'xrandr -o normal && xrandr --dpi 96'

    suspend: | # put laptop to sleep
      action 'pomodoro_pause'
      action 'laptop'
      system 'sudo /etc/rc.d/networkmanager stop'
      #launch 'xlock' # password protection
      system 'sudo pm-suspend'
      system 'sudo /etc/rc.d/networkmanager start'
      action 'autotop'

  mouse:
    grab: Mod4

  keyboard:
    up:      k
    down:    j
    left:    h
    right:   l
    root:    Mod4-
    send:    ${root}Shift-
    size:    ${root}Control-
    swap:    ${root}w,
    view:    ${root}v,
    group:   ${root}g,
    layout:  ${root}z,

  keyboard_action:
    XF86Display:              negative
    ${root}x:                 terminal
    ${root}b:                 browser
    F9:                       nein

    #-------------------------------------------------------------------------
    # basic
    #-------------------------------------------------------------------------

    ${root}i:                 action_menu
    ${root}p:                 launch_menu

    #-------------------------------------------------------------------------
    # client
    #-------------------------------------------------------------------------

    ${root}a:                 focus_client_menu
    ${root}Shift-a:           client_invite_menu
    ${root}f:                 client_fullscreen!

    ${root}${up}:             focus_client_up
    ${root}${down}:           focus_client_down
    ${root}${left}:           focus_client_left
    ${root}${right}:          focus_client_right
    ${size}comma:             focus_client_view_previous
    ${size}period:            focus_client_view_next

    ${size}${up}:             resize_client_up
    ${size}${down}:           resize_client_down
    ${size}${left}:           resize_client_left
    ${size}${right}:          resize_client_right
    ${size}Shift-${up}:       shrink_client_up
    ${size}Shift-${down}:     shrink_client_down
    ${size}Shift-${left}:     shrink_client_left
    ${size}Shift-${right}:    shrink_client_right

    ${send}${up}:             send_group_up
    ${send}${down}:           send_group_down
    ${send}${left}:           send_group_left
    ${send}${right}:          send_group_right

    ${send}t:                 send_group_view_menu
    ${send}space:             send_group_overlay!
    ${send}c:                 group_kill

    ${send}1:                 send_group_view_1
    ${send}2:                 send_group_view_2
    ${send}3:                 send_group_view_3
    ${send}4:                 send_group_view_4
    ${send}5:                 send_group_view_5
    ${send}6:                 send_group_view_6
    ${send}7:                 send_group_view_7
    ${send}8:                 send_group_view_8
    ${send}9:                 send_group_view_9
    ${send}0:                 send_group_view_0

    ${swap}${up}:             swap_client_up
    ${swap}${down}:           swap_client_down
    ${swap}${left}:           swap_client_left
    ${swap}${right}:          swap_client_right
    ${root}Return:            swap_client_master

    ${swap}1:                 swap_client_column_1
    ${swap}2:                 swap_client_column_2
    ${swap}3:                 swap_client_column_3
    ${swap}4:                 swap_client_column_4
    ${swap}5:                 swap_client_column_5
    ${swap}6:                 swap_client_column_6
    ${swap}7:                 swap_client_column_7
    ${swap}8:                 swap_client_column_8
    ${swap}9:                 swap_client_column_9
    ${swap}0:                 swap_client_column_0

    #-------------------------------------------------------------------------
    # area
    #-------------------------------------------------------------------------

    ${root}space:             focus_overlay!

    #-------------------------------------------------------------------------
    # view
    #-------------------------------------------------------------------------

    ${root}comma:             focus_view_previous
    ${root}period:            focus_view_next
    ${root}o:                 focus_view_recent
    ${root}t:                 focus_view_menu

    ${root}1:                 focus_view_1
    ${root}2:                 focus_view_2
    ${root}3:                 focus_view_3
    ${root}4:                 focus_view_4
    ${root}5:                 focus_view_5
    ${root}6:                 focus_view_6
    ${root}7:                 focus_view_7
    ${root}8:                 focus_view_8
    ${root}9:                 focus_view_9
    ${root}0:                 focus_view_0

    ${view}a:                 focus_view_a
    ${view}b:                 focus_view_b
    ${view}c:                 focus_view_c
    ${view}d:                 focus_view_d
    ${view}e:                 focus_view_e
    ${view}f:                 focus_view_f
    ${view}g:                 focus_view_g
    ${view}h:                 focus_view_h
    ${view}i:                 focus_view_i
    ${view}j:                 focus_view_j
    ${view}k:                 focus_view_k
    ${view}l:                 focus_view_l
    ${view}m:                 focus_view_m
    ${view}n:                 focus_view_n
    ${view}o:                 focus_view_o
    ${view}p:                 focus_view_p
    ${view}q:                 focus_view_q
    ${view}r:                 focus_view_r
    ${view}s:                 focus_view_s
    ${view}t:                 focus_view_t
    ${view}u:                 focus_view_u
    ${view}v:                 focus_view_v
    ${view}w:                 focus_view_w
    ${view}x:                 focus_view_x
    ${view}y:                 focus_view_y
    ${view}z:                 focus_view_z

    #-------------------------------------------------------------------------
    # layout
    #-------------------------------------------------------------------------

    ${layout}m:               layout_column_equal
    ${layout}comma:               layout_column_stack
    ${layout}period:               layout_column_max

    ${layout}Shift-m:         layout_view_equal
    ${layout}Shift-comma:         layout_view_stack
    ${layout}Shift-period:         layout_view_max

    ${layout}r:               arrange_right
    ${layout}Control-r:       arrange_right_persist
    ${layout}Shift-r:         arrange_rightward
    ${layout}Control-Shift-r: arrange_rightward_persist
    ${layout}l:               arrange_left
    ${layout}Control-l:       arrange_left_persist
    ${layout}Shift-l:         arrange_leftward
    ${layout}Control-Shift-l: arrange_leftward_persist
    ${layout}i:               arrange_inward
    ${layout}Control-i:       arrange_inward_persist
    ${layout}o:               arrange_outward
    ${layout}Control-o:       arrange_outward_persist
    ${layout}g:               arrange_grid
    ${layout}Control-g:       arrange_grid_persist
    ${layout}s:               arrange_stack
    ${layout}Control-s:       arrange_stack_persist
    ${layout}j:               arrange_join
    ${layout}Control-j:       arrange_join_persist
    ${layout}Shift-j:         arrange_split
    ${layout}Control-Shift-j: arrange_split_persist
    ${layout}z:               arrange_persist_redo
    ${layout}Control-z:       arrange_persist_stop
    ${layout}Shift-z:         arrange_persist_menu

    #-------------------------------------------------------------------------
    # group
    #-------------------------------------------------------------------------

    ${group}g:                group_client!
    ${group}c:                group_area!
    ${group}a:                group_columns!
    ${group}space:                group_overlay!
    ${group}t:                group_view!
    ${group}w:                group_all!
    ${group}n:                ungroup_all

    ${size}2:                 zoom_group
    ${size}1:                 unzoom_group

    ${size}0:                 detach_group
    ${size}9:                 attach_client

    #-------------------------------------------------------------------------
    # volume
    #-------------------------------------------------------------------------

    XF86AudioRaiseVolume:     volume_more
    XF86AudioLowerVolume:     volume_less
    XF86AudioMute:            volume_mute!

    ${send}Prior:             volume_more
    ${send}Next:              volume_less

    #-------------------------------------------------------------------------
    # music
    #-------------------------------------------------------------------------

    XF86AudioPlay:            music_play!
    XF86AudioPrev:            music_previous
    XF86AudioNext:            music_next
    XF86AudioStop:            music_stop

    ${size}Return:            music_play!
    ${size}Home:              music_previous
    ${size}End:               music_next

#- script:
#  - after: |
#      launch 'killall -u amukherjee -0 gnome-settings-daemon || gnome-settings-daemon'
#      launch 'killall -u amukherjee -0 clipit || clipit'
#      launch 'killall -u amukherjee -0 pidgin || pidgin'
#      launch 'dropbox start'
#      launch 'thunderbird'
#      launch 'killall -u amukherjee -0 wallpaper.sh || /home/amukherjee/bin/wallpaper.sh'

