control:
  action:

    action_menu: |
      if choice = key_menu(actions, 'action:', :action)
        action choice
      end

    reload: |
      # reload this wmii configuration
      Wmiirc::Loader.reload

    clear: |
      # these browsers' "restore session" feature does
      # not work unless the whole process group is killed
      system 'killall', 'opera',
        'chromium', 'chromium-browser',
        'firefox', 'firefox-bin',
        'thunderbird', 'thunderbird-bin'

      clients.each {|c| c.kill rescue nil }

    kill: |
      # kill the window manager only; do not touch the clients!
      fs.ctl.write 'quit'

    quit: |
      # kill both clients and window manager
      action 'clear'
      action 'kill'
